# Generated by Django 4.1.7 on 2023-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLivro', models.CharField(max_length=60)),
                ('anoLivro', models.IntegerField()),
                ('autorLivro', models.CharField(max_length=50)),
                ('paginasLivro', models.IntegerField()),
            ],
        ),
    ]
